### ISSUE TITLE
Assignment 1 Ready For Grading

### ISSUE THREAD

**Issue by sage-grey-voorhees** [VIS-2129-F2020/svoorhees-vis#1]
Thank you so much!

**Comment by bauranov** [comment]
This looks great, good work!

- Line 125: Instead of GGPLOT1, GGPLOT2... maybe it would be better if you named the plots by type (Scatter plot 1, Box plot 1, Box plot 2).
- Lines 155-160: The chart would be more legible if there was more contrast between the background and the dots. Either try removing the background, make the dots bigger, or change the dot color. 
- Line 198: Add another row between the code chunk and the text to avoid weird formatting in the HTML file. 
- Line 211: Add "+" after the scale_x_continuous.
- Lines 215: Same as 198.
- GGPLOT5 is not too informative, but I can't stop looking at it. It should be a print on the t-shirt. 

Next time please add a link to the assignment in the comment of the issue (https://vis-2129-f2020.github.io/svoorhees-vis/assignment_name)
Keep up the good work!
