### ISSUE TITLE
Stuck on Join

### ISSUE THREAD

**Issue by sage-grey-voorhees** [VIS-2129-F2020/svoorhees-vis#3]
Hi! I'm stuck trying to join two dataframes. 

Could you help me figure out why this join isn't working in **lines 206-216?**
 I'm getting the error "Error: Join columns must be present in data. x Problem with `Var1`."

I've been looking at past examples of joins, and I'm not catching where the error is. 

https://github.com/VIS-2129-F2020/svoorhees-vis/blob/master/Assignment3_VIS_REAL.Rmd

**Comment by bauranov** [comment]
Hi Sage,
- You have a %>% at the end of line 209 that should be deleted.
- Since bos_zip_code is the first to appear in the function in Line 212, bos_zip_code it is the *left* data frame, and freq_stops is the *right* df. Column names in by = c() should also be in that order, so by =c("ZIP5"="Var1").
- I think there's no need for bos_zip_code %>%as.data.frame(), I could be wrong.
- Finally, the variable used to name the zipcodes is not ZIPS, but ZIP5. That's the case in a majority of data bases in the US, I have no idea why.

The final code is:

freq_stop <- as.data.frame(table(unlist(fio_records$zip))) 
zip_stops <- bos_zip_code %>%
  left_join(freq_stop, by =c("ZIP5" = "Var1"))%>%
  select(ZIP5, Freq, OBJECTID,geometry)
